{"name": "test_demo2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'd' in 'hello'", "trace": "self = <demo.demo2.test_RequestDemo1.TestClass object at 0x0000017D87FE1EE0>\n\n    @allure.story(\"测试用例2\")\n    def test_demo2(self):\n        x = \"hello\"\n>       assert \"d\" in x\nE       AssertionError: assert 'd' in 'hello'\n\ntest_RequestDemo1.py:55: AssertionError"}, "start": 1621218790033, "stop": 1621218790034, "uuid": "3bec99e2-ac96-46af-a977-707f75d970b6", "historyId": "2c15a350a79e51a925d7e6b0f55cd04c", "testCaseId": "3afb4ead01ba1f08a579af572c1dde7a", "fullName": "test_RequestDemo1.TestClass#test_demo2", "labels": [{"name": "feature", "value": "测试Demo"}, {"name": "story", "value": "测试用例2"}, {"name": "suite", "value": "test_RequestDemo1"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-5E3GPA5"}, {"name": "thread", "value": "9636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_RequestDemo1"}]}